version: '3.0'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - /home/mario/project/src/__tests__:/usr/src/app/__tests__ 
      
